<?php
// Plugin definition
$plugin = array(
  'title' => t('Aloha'),
  'icon' => 'aloha.png',
  'category' => t('Signage Admin'),
  'theme' => 'aloha',
  'css' => 'aloha.css',
  'regions' => array(
    'row-one' => t('Row One'),
    'row-two-left' => t('Row Two Left'),
    'row-two-right' => t('Row Two Right'),
    'row-three' => t('Row Three'),
    'row-four-left' => t('Row Four Left'),
    'row-four-middle' => t('Row Four Middle'),
    'row-four-right' => t('Row Four Right'),
  ),
);
