# Pull gems from RubyGems
source 'https://rubygems.org'

group :development do

  # Sass, Compass and extensions.
  gem 'breakpoint', '~> 2.4.1'
  gem 'compass', '~> 1.0.1'
  gem 'compass-normalize', '~> 1.5'
  gem 'sass-globbing', '~> 1.1.1'
  gem 'sass', '~> 3.3'
  gem 'singularitygs', '~> 1.6.2'
  gem 'toolkit', '~> 2.9.0'

end
